In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style='whitegrid', palette='viridis')

# Configuracion de pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.4f}'.format)

In [13]:
df = pd.read_csv('uber_fares.csv')

print(f'Dimensiones del dataset: {df.shape[0]} filas x {df.shape[1]} columnas')
df.head(10)

Dimensiones del dataset: 200000 filas x 9 columnas

,key,date,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:50:00,8.4700,2015-05-07 19:50:00 UTC,-73.9998,40.7384,-73.9995,40.7232,1
1,27835199,2009-07-17 20:00:04,7.6000,2009-07-17 20:00:04 UTC,-73.9944,40.7282,-73.9947,40.7503,1
2,44984355,2009-08-24 21:49:07,12.6500,2009-08-24 21:49:07 UTC,-74.0050,40.7408,-73.9626,40.7726,1
3,25894730,2009-06-26 08:17:45,5.0100,2009-06-26 08:17:45 UTC,-73.9761,40.7908,-73.9653,40.8033,3
4,17610152,2014-08-28 17:46:18,15.6400,2014-08-28 17:46:18 UTC,-73.9250,40.7441,-73.9731,40.7612,5
5,44470845,2011-02-12 02:28:47,4.0500,2011-02-12 02:28:47 UTC,-73.9690,40.7559,-73.9690,40.7559,1
6,48725865,2014-10-12 07:01:25,26.7300,2014-10-12 07:01:25 UTC,-73.9614,40.6940,-73.8712,40.7743,5
7,44195482,2012-12-11 13:53:11,2.7000,2012-12-11 13:53:11 UTC,0.0000,0.0000,0.0000,0.0000,1
8,15822268,2012-02-17 09:34:14,9.5000,2012-02-17 09:34:14 UTC,-73.9752,40.7458,-74.0027,40.7435,1
9,50611056,2012-03-29 19:03:22,12.5300,2012-03-29 19:03:22 UTC,-74.0011,40.7418,-73.9630,40.7750,1

In [14]:
# Inspeccion de tipos de datos y estructura
print('Tipos de datos y valores no nulos:')
print('=' * 50)
df.info()

Tipos de datos y valores no nulos:
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   key                200000 non-null  int64
 1   date               200000 non-null  str
 2   fare_amount        200000 non-null  float64
 3   pickup_datetime    200000 non-null  str
 4   pickup_longitude   200000 non-null  float64
 5   pickup_latitude    200000 non-null  float64
 6   dropoff_longitude  199999 non-null  float64
 7   dropoff_latitude   199999 non-null  float64
 8   passenger_count    200000 non-null  int64
dtypes: float64(5), int64(2), str(2)
memory usage: 13.7 MB

Parece que tenemos todas columnas numéricas, salvo 2 que se intencionan como datetime pero con la carga existen como string. También hay 2 valores nulos en todo el dataset: uno en dropoff_latitude y otro en dropoff_longitude.

In [15]:
# Filtramos el dataframe para mostrar solo las filas que tienen al menos un valor nulo
filas_nulas = df[df.isnull().any(axis=1)]

print("Filas con valores faltantes:")
filas_nulas

Filas con valores faltantes:

,key,date,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
87946,32736015,2013-07-02 03:53:05,24.1500,2013-07-02 03:53:05 UTC,-73.9506,40.7797,NaN,NaN,0

Parece ser una fila rara, que no tiene pasajeros, a pesar de existir una tarifa por ese viaje. Es una sola fila y que tiene varios problemas, así que la eliminamos.

In [22]:
df.dropna(inplace=True)

df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])

df['date'] = pd.to_datetime(df['date'])

print(df[['date', 'pickup_datetime']].dtypes)
print('=' * 50)
df.info()
print('=' * 80)
df.head()

date                    datetime64[us]
pickup_datetime    datetime64[us, UTC]
dtype: object
==================================================
<class 'pandas.DataFrame'>
Index: 199999 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   key                199999 non-null  int64
 1   date               199999 non-null  datetime64[us]
 2   fare_amount        199999 non-null  float64
 3   pickup_datetime    199999 non-null  datetime64[us, UTC]
 4   pickup_longitude   199999 non-null  float64
 5   pickup_latitude    199999 non-null  float64
 6   dropoff_longitude  199999 non-null  float64
 7   dropoff_latitude   199999 non-null  float64
 8   passenger_count    199999 non-null  int64
dtypes: datetime64[us, UTC](1), datetime64[us](1), float64(5), int64(2)
memory usage: 15.3 MB
================================================================================

,key,date,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:50:00,8.4700,2015-05-07 19:50:00+00:00,-73.9998,40.7384,-73.9995,40.7232,1
1,27835199,2009-07-17 20:00:04,7.6000,2009-07-17 20:00:04+00:00,-73.9944,40.7282,-73.9947,40.7503,1
2,44984355,2009-08-24 21:49:07,12.6500,2009-08-24 21:49:07+00:00,-74.0050,40.7408,-73.9626,40.7726,1
3,25894730,2009-06-26 08:17:45,5.0100,2009-06-26 08:17:45+00:00,-73.9761,40.7908,-73.9653,40.8033,3
4,17610152,2014-08-28 17:46:18,15.6400,2014-08-28 17:46:18+00:00,-73.9250,40.7441,-73.9731,40.7612,5

In [23]:
# Separacion de variables por tipo
cols_numericas = df.select_dtypes(include=[np.number]).columns.tolist()
cols_categoricas = df.select_dtypes(include=['category', 'object']).columns.tolist()

desc = df[cols_numericas].describe().T
desc['mediana'] = df[cols_numericas].median()
desc['CV(%)'] = (desc['std'] / desc['mean']) * 100
desc['sesgo'] = df[cols_numericas].skew()
desc['curtosis'] = df[cols_numericas].kurtosis()

print('Estadisticos descriptivos completos:')
print('=' * 80)
desc[['mean', 'mediana', 'std', 'CV(%)', 'min', '25%', '50%', '75%', 'max',
      'sesgo', 'curtosis']]

Estadisticos descriptivos completos:
================================================================================

,mean,mediana,std,CV(%),min,25%,50%,75%,max,sesgo,curtosis
key,27712478.5647,27745245.0000,16013858.3080,57.7857,1.0000,13825336.5000,27745245.0000,41555348.5000,55423567.0000,-0.0018,-1.2003
fare_amount,11.3629,8.4300,9.9432,87.5065,1.0000,5.9700,8.4300,12.6600,503.1300,4.4823,62.2469
pickup_longitude,-72.5276,-73.9818,11.4378,-15.7703,-1340.6484,-73.9921,-73.9818,-73.9672,57.4185,-7.4959,1144.0219
pickup_latitude,39.9359,40.7526,7.7206,19.3324,-74.0155,40.7348,40.7526,40.7672,1644.4215,62.9767,12869.1778
dropoff_longitude,-72.5253,-73.9801,13.1174,-18.0867,-3356.6663,-73.9914,-73.9801,-73.9637,1153.5726,-71.5051,20078.7229
dropoff_latitude,39.9239,40.7530,6.7948,17.0195,-881.9855,40.7338,40.7530,40.7680,872.6976,-8.0310,2981.7419
passenger_count,1.6845,1.0000,1.3860,82.2772,0.0000,1.0000,1.0000,2.0000,208.0000,18.1457,2456.6454

passenger_count no puede ser 0. Hay que revisar cuantas son con pasajeros 0, y qué pasaba en esas filas. Además, las longitudes deben estar entre -180 y 180, y las latitudes entre -90 y 90. Hay que analizar todas las filas que están fuera de este rango.

**1. Limpieza de Outliers para Visualización**

In [ ]:
# Filtro rápido para que las gráficas sean interpretables
#Para que un histograma o un scatterplot no se vea "aplastado" por valores extremos (como esa latitud de 1644)
df_plot = df[
    (df['fare_amount'] > 0) & (df['fare_amount'] < 100) &
    (df['passenger_count'] > 0) & (df['passenger_count'] < 7) &
    (df['pickup_longitude'].between(-75, -72)) &
    (df['pickup_latitude'].between(40, 42))
].copy()

print(f"Datos tras limpieza para gráficas: {df_plot.shape[0]}")

**2. Visualizaciones (Histogramas, Boxplots y Scatterplots)**

In [ ]:
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# 1. Histograma: Distribución de la Tarifa
sns.histplot(df_plot['fare_amount'], bins=50, kde=True, ax=axes[0, 0], color='teal')
axes[0, 0].set_title('Distribución de fare_amount (Tarifas < $100)')

# 2. Boxplot: Tarifa por cantidad de pasajeros
sns.boxplot(x='passenger_count', y='fare_amount', data=df_plot, ax=axes[0, 1])
axes[0, 1].set_title('Boxplot: fare_amount vs passenger_count')

# 3. Scatterplot: Relación entre ubicación (Pickup)
# Usamos un sample para no saturar el gráfico
sns.scatterplot(x='pickup_longitude', y='pickup_latitude', data=df_plot.sample(5000), 
                alpha=0.3, ax=axes[1, 0], s=10)
axes[1, 0].set_title('Scatterplot: Geolocalización de Pickups (Sample)')

# 4. Boxplot: Detección de outliers en fare_amount
sns.boxplot(x=df_plot['fare_amount'], ax=axes[1, 1], color='lightcoral')
axes[1, 1].set_title('Boxplot de fare_amount (Detección de Outliers)')

plt.tight_layout()
plt.show()

****3. Matriz de Correlación**

In [ ]:
#La correlación nos dirá qué variables numéricas se mueven juntas.

plt.figure(figsize=(10, 8))

# Calculamos correlación solo de columnas numéricas relevantes
corr_matrix = df_plot[['fare_amount', 'pickup_longitude', 'pickup_latitude', 
                       'dropoff_longitude', 'dropoff_latitude', 'passenger_count']].corr()

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Matriz de Correlación de Variables Numéricas')
plt.show()

**Notas sobre los resultados:**
**Histograma:** Hay un sesgo a la derecha es normal en precios, muchos viajes baratos y pocos muy caros

**Boxplots:** Ayuda a confirmar si el número de pasajeros influye realmente en el costo (En Uber no suele influir tanto como la distancia).

**Correlación:** Se ven correlaciones bajas entre coordenadas y tarifa directamente.